package com.loserstar.entity;

import com.loserstar.entity.base.BaseDaAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaAccount extends BaseDaAccount<DaAccount> {
	public static final DaAccount dao = new DaAccount().dao();
}
