package com.loserstar.entity;

import com.loserstar.entity.base.BaseDaAccount;
import java.io.Serializable;

/** 实体类
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DaAccount extends BaseDaAccount<DaAccount> implements Serializable{
	public static final String TABLE_NAME = "da_account";
	public static final String PRIMARY_KEY = "id";
	public static final String SOFT_DEL_FIELD= "DEL";
	
	public static final DaAccount dao = new DaAccount().dao();
}
