package com.loserstar.entity;

import com.loserstar.entity.base.BaseSysDict;
import java.io.Serializable;

/** 实体类
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysDict extends BaseSysDict<SysDict> implements Serializable{
	public static final String TABLE_NAME = "loserStar.sys_dict";
	public static final String PRIMARY_KEY = "dict_id";
	public static final String SOFT_DEL_FIELD= "";
	
	public static final SysDict dao = new SysDict().dao();
}
