package com.loserstar.entity;

import com.loserstar.entity.base.BaseSysUsers;
import java.io.Serializable;

/** 实体类
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUsers extends BaseSysUsers<SysUsers> implements Serializable{
	public static final String TABLE_NAME = "loserStar.sys_users";
	public static final String PRIMARY_KEY = "id";
	public static final String SOFT_DEL_FIELD= "DEL";
	
	public static final SysUsers dao = new SysUsers().dao();
}
