package com.loserstar.entity;

import com.loserstar.entity.base.BaseSysUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUsers extends BaseSysUsers<SysUsers> {
	public static final SysUsers dao = new SysUsers().dao();
}
