package com.loserstar.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysDict<M extends BaseSysDict<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setDictId(java.lang.String dictId) {
		set("dict_id", dictId);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getDictId() {
		return getStr("dict_id");
	}

	/**
	 * 值
	 */
	public M setDictValue(java.lang.String dictValue) {
		set("dict_value", dictValue);
		return (M)this;
	}
	
	/**
	 * 值
	 */
	public java.lang.String getDictValue() {
		return getStr("dict_value");
	}

	/**
	 * 名称
	 */
	public M setDictName(java.lang.String dictName) {
		set("dict_name", dictName);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getDictName() {
		return getStr("dict_name");
	}

	/**
	 * 类型
	 */
	public M setDictType(java.lang.String dictType) {
		set("dict_type", dictType);
		return (M)this;
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getDictType() {
		return getStr("dict_type");
	}

	/**
	 * 备注
	 */
	public M setDictRemarks(java.lang.String dictRemarks) {
		set("dict_remarks", dictRemarks);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getDictRemarks() {
		return getStr("dict_remarks");
	}

	/**
	 * java后端使用的常量名称
	 */
	public M setDictCName(java.lang.String dictCName) {
		set("dict_c_name", dictCName);
		return (M)this;
	}
	
	/**
	 * java后端使用的常量名称
	 */
	public java.lang.String getDictCName() {
		return getStr("dict_c_name");
	}

	/**
	 * 前端附加的样式
	 */
	public M setDictCssStyle(java.lang.String dictCssStyle) {
		set("dict_css_style", dictCssStyle);
		return (M)this;
	}
	
	/**
	 * 前端附加的样式
	 */
	public java.lang.String getDictCssStyle() {
		return getStr("dict_css_style");
	}

	/**
	 * 排序码
	 */
	public M setDictSort(java.lang.Integer dictSort) {
		set("dict_sort", dictSort);
		return (M)this;
	}
	
	/**
	 * 排序码
	 */
	public java.lang.Integer getDictSort() {
		return getInt("dict_sort");
	}

	/**
	 * 删除标志
	 */
	public M setDel(java.lang.String del) {
		set("del", del);
		return (M)this;
	}
	
	/**
	 * 删除标志
	 */
	public java.lang.String getDel() {
		return getStr("del");
	}

}
