package com.loserstar.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysFile<M extends BaseSysFile<M>> extends Model<M> implements IBean {

	/**
	 * 主键id
	 */
	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键id
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 文件存储路径
	 */
	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	/**
	 * 文件存储路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 上传日期
	 */
	public M setUploadTime(java.util.Date uploadTime) {
		set("upload_time", uploadTime);
		return (M)this;
	}
	
	/**
	 * 上传日期
	 */
	public java.util.Date getUploadTime() {
		return get("upload_time");
	}

	/**
	 * 排序
	 */
	public M setSort(java.lang.Long sort) {
		set("sort", sort);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Long getSort() {
		return getLong("sort");
	}

	/**
	 * 软删除字段
	 */
	public M setDel(java.lang.String del) {
		set("del", del);
		return (M)this;
	}
	
	/**
	 * 软删除字段
	 */
	public java.lang.String getDel() {
		return getStr("del");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 创建人编号
	 */
	public M setCreateUserCode(java.lang.String createUserCode) {
		set("create_user_code", createUserCode);
		return (M)this;
	}
	
	/**
	 * 创建人编号
	 */
	public java.lang.String getCreateUserCode() {
		return getStr("create_user_code");
	}

	/**
	 * 创建人姓名
	 */
	public M setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
		return (M)this;
	}
	
	/**
	 * 创建人姓名
	 */
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 更新人编号
	 */
	public M setUpdateUserCode(java.lang.String updateUserCode) {
		set("update_user_code", updateUserCode);
		return (M)this;
	}
	
	/**
	 * 更新人编号
	 */
	public java.lang.String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	/**
	 * 更新人姓名
	 */
	public M setUpdateUserName(java.lang.String updateUserName) {
		set("update_user_name", updateUserName);
		return (M)this;
	}
	
	/**
	 * 更新人姓名
	 */
	public java.lang.String getUpdateUserName() {
		return getStr("update_user_name");
	}

	/**
	 * 文件后缀
	 */
	public M setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
		return (M)this;
	}
	
	/**
	 * 文件后缀
	 */
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}

	/**
	 * 附件所属记录id
	 */
	public M setFromId(java.lang.String fromId) {
		set("from_id", fromId);
		return (M)this;
	}
	
	/**
	 * 附件所属记录id
	 */
	public java.lang.String getFromId() {
		return getStr("from_id");
	}

	/**
	 * 附件所属记录的表
	 */
	public M setFromTable(java.lang.String fromTable) {
		set("from_table", fromTable);
		return (M)this;
	}
	
	/**
	 * 附件所属记录的表
	 */
	public java.lang.String getFromTable() {
		return getStr("from_table");
	}

}
